import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { objectDigest, deepFreeze } from './records.mjs';
import { readIfExists } from './repo-source.mjs';

/**
 * Narrow M1.1 license scanner. It is an engineering gate, NOT a legal parser
 * and NOT legal advice. It recognizes a fixed set of common SPDX identifiers
 * from root LICENSE/COPYING text, the package.json `license` field and
 * runtime `dependencies` metadata. Anything mixed (AND/WITH/exception),
 * conflicting between evidence sources, unparseable or missing falls back to
 * conservative review_required / blocked. File-level SPDX headers are M2 scope.
 */

export const LICENSE_DISCLAIMER = 'This license report is generated by automated scanning and is provided for informational purposes only. It does not constitute legal advice. The absence of a detected license does not grant permission to use the source code.';

const PERMISSIVE = {
  MIT: { spdx: 'MIT', obligations: ['notice'] },
  'MIT-0': { spdx: 'MIT-0', obligations: [] },
  'Apache-2.0': { spdx: 'Apache-2.0', obligations: ['notice'] },
  'BSD-2-Clause': { spdx: 'BSD-2-Clause', obligations: ['notice'] },
  'BSD-3-Clause': { spdx: 'BSD-3-Clause', obligations: ['notice'] },
  ISC: { spdx: 'ISC', obligations: ['notice'] },
  Unlicense: { spdx: 'Unlicense', obligations: [] },
  'CC0-1.0': { spdx: 'CC0-1.0', obligations: [] },
};
const COPYLEFT_REVIEW = {
  'GPL-2.0-only': ['corresponding_source', 'same_license'],
  'GPL-2.0-or-later': ['corresponding_source', 'same_license'],
  'GPL-3.0-only': ['corresponding_source', 'same_license'],
  'GPL-3.0-or-later': ['corresponding_source', 'same_license'],
  'LGPL-2.1-only': ['source_offer', 'same_license'],
  'LGPL-2.1-or-later': ['source_offer', 'same_license'],
  'LGPL-3.0-only': ['source_offer', 'same_license'],
  'LGPL-3.0-or-later': ['source_offer', 'same_license'],
};
const COPYLEFT_BLOCKED = {
  'AGPL-3.0-only': ['corresponding_source', 'same_license'],
  'AGPL-3.0-or-later': ['corresponding_source', 'same_license'],
};

/** Classify root license text by canonical markers. Returns an SPDX id or null. */
export function classifyLicenseText(text) {
  if (!text) return null;
  const head = text.slice(0, 20000);
  if (/GNU AFFERO GENERAL PUBLIC LICENSE/i.test(head)) return /Version 3/i.test(head) ? 'AGPL-3.0-only' : 'AGPL-3.0-only';
  if (/GNU LESSER GENERAL PUBLIC LICENSE/i.test(head)) return /Version 3/i.test(head) ? 'LGPL-3.0-only' : 'LGPL-2.1-only';
  if (/GNU GENERAL PUBLIC LICENSE/i.test(head)) return /Version 3/i.test(head) ? 'GPL-3.0-only' : 'GPL-2.0-only';
  if (/Apache License/i.test(head) && /Version 2\.0/i.test(head)) return 'Apache-2.0';
  if (/MIT License/i.test(head) || (/Permission is hereby granted, free of charge/i.test(head) && /THE SOFTWARE IS PROVIDED "AS IS"/i.test(head))) return 'MIT';
  if (/Redistribution and use in source and binary forms/i.test(head)) return /Neither the name/i.test(head) ? 'BSD-3-Clause' : 'BSD-2-Clause';
  if (/ISC License/i.test(head) || /Permission to use, copy, modify, and\/or distribute this software/i.test(head)) return 'ISC';
  if (/This is free and unencumbered software released into the public domain/i.test(head)) return 'Unlicense';
  if (/CC0 1\.0 Universal/i.test(head)) return 'CC0-1.0';
  return null;
}

/** Parse a package.json `license` field. Compound/exception expressions stay intact. */
export function parseLicenseExpression(value) {
  if (typeof value !== 'string' || value.trim().length === 0) return { kind: 'missing' };
  const expression = value.trim();
  if (/\bAND\b/i.test(expression) || /\bWITH\b/i.test(expression) || /[()]/.test(expression)) return { kind: 'compound', expression };
  if (/\bOR\b/i.test(expression)) return { kind: 'choice', expression, options: expression.split(/\s+OR\s+/i).map(part => part.trim()) };
  if (/^(UNLICENSED|proprietary|all rights reserved)$/i.test(expression)) return { kind: 'proprietary', expression };
  const id = expression.replace(/[+\s]+$/, '');
  if (PERMISSIVE[id] || COPYLEFT_REVIEW[id] || COPYLEFT_BLOCKED[id]) return { kind: 'single', spdx: id };
  return { kind: 'unparseable', expression };
}

function entryFor(spdx, source, scope, confidence) {
  return { spdx, source, scope, confidence };
}

/**
 * Scan a snapshotted local repo into a LicenseReport.
 * dependency closure: runtime `dependencies` only, resolved from each dep's own
 * node_modules/<dep>/package.json license field when present; absent metadata is
 * recorded as unresolved evidence, never silently assumed permissive.
 */
export async function scanLicense(repoDir, snapshot) {
  const detected = [];
  const conflicts = [];
  const obligations = new Set();
  const evidence = [];
  let rootSpdx = null;
  for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'COPYING']) {
    const text = await readIfExists(repoDir, name);
    if (text === null) continue;
    evidence.push(name);
    const spdx = classifyLicenseText(text);
    if (spdx) { rootSpdx = spdx; detected.push(entryFor(spdx, name, 'source', 0.9)); }
    else detected.push({ spdx: null, source: name, scope: 'source', confidence: 0.2, note: 'license text present but not recognized by the narrow scanner' });
    break;
  }
  const pkgText = await readIfExists(repoDir, 'package.json');
  let pkg = {};
  if (pkgText !== null) {
    evidence.push('package.json');
    pkg = JSON.parse(pkgText);
    const expression = parseLicenseExpression(pkg.license);
    if (expression.kind === 'single') detected.push(entryFor(expression.spdx, 'package.json', 'source', 0.8));
    else if (expression.kind === 'compound') detected.push({ spdx: null, source: 'package.json', scope: 'source', confidence: 0.6, note: `compound expression requires review: ${expression.expression}` });
    else if (expression.kind === 'choice') detected.push({ spdx: null, source: 'package.json', scope: 'source', confidence: 0.6, note: `dual-license choice requires an explicit user decision: ${expression.expression}` });
    else if (expression.kind === 'proprietary') detected.push({ spdx: null, source: 'package.json', scope: 'source', confidence: 0.9, note: `proprietary marker: ${expression.expression}` });
  }
  // Cross-evidence conflict: never trust a single source.
  const pkgSingle = pkg.license ? parseLicenseExpression(pkg.license) : { kind: 'missing' };
  if (rootSpdx && pkgSingle.kind === 'single' && pkgSingle.spdx !== rootSpdx) {
    conflicts.push(`LICENSE file is ${rootSpdx} but package.json declares ${pkgSingle.spdx}`);
  }
  // A bare package.json declaration without the full root license text is
  // insufficient evidence for automatic delivery (deleted-LICENSE case).
  if (!rootSpdx && pkgSingle.kind === 'single') conflicts.push(`package.json declares ${pkgSingle.spdx} but no root LICENSE/COPYING file carries the full text`);
  if (pkgSingle.kind === 'compound') conflicts.push(`compound SPDX expression requires review: ${pkgSingle.expression}`);
  if (pkgSingle.kind === 'choice') conflicts.push(`license choice expression requires an explicit decision: ${pkgSingle.expression}`);
  // Runtime dependency closure (stable digest over sorted name@version+license entries).
  const closure = [];
  const dependencies = Object.keys(pkg.dependencies ?? {}).sort();
  for (const dep of dependencies) {
    const depPkg = await readIfExists(repoDir, join('node_modules', dep, 'package.json'));
    if (depPkg === null) {
      closure.push({ name: dep, version: pkg.dependencies[dep], license: null, evidence: 'unresolved' });
      detected.push({ spdx: null, source: `node_modules/${dep}/package.json`, scope: 'dependency', confidence: 0, note: 'dependency metadata not vendored; license unresolved' });
      continue;
    }
    try {
      const parsed = JSON.parse(depPkg);
      const depExpr = parseLicenseExpression(parsed.license);
      const spdx = depExpr.kind === 'single' ? depExpr.spdx : null;
      closure.push({ name: dep, version: parsed.version ?? pkg.dependencies[dep], license: spdx ?? parsed.license ?? null, evidence: `node_modules/${dep}/package.json` });
      detected.push({ spdx, source: `node_modules/${dep}/package.json`, scope: 'dependency', confidence: spdx ? 0.8 : 0.2, ...(spdx ? {} : { note: `dependency license unresolved: ${parsed.license ?? 'missing'}` }) });
    } catch {
      closure.push({ name: dep, version: pkg.dependencies[dep], license: null, evidence: 'unparseable' });
      detected.push({ spdx: null, source: `node_modules/${dep}/package.json`, scope: 'dependency', confidence: 0, note: 'dependency package.json unparseable' });
    }
  }
  const lockText = await readIfExists(repoDir, 'package-lock.json');
  if (lockText !== null) evidence.push('package-lock.json');
  const depEntries = closure.map(entry => `${entry.name}@${entry.version}:${entry.license ?? 'UNRESOLVED'}`).sort();
  // Dependency conflicts are real conflicts: a copyleft dependency is never
  // overridden by the permissive name of the root project.
  for (const item of detected.filter(item => item.scope === 'dependency' && item.spdx)) {
    if (COPYLEFT_REVIEW[item.spdx] || COPYLEFT_BLOCKED[item.spdx]) conflicts.push(`dependency ${item.source} is ${item.spdx} (copyleft in dependency closure)`);
  }
  const unresolvedDep = closure.some(entry => entry.license === null);
  // Decision.
  const all = detected.filter(item => item.spdx);
  const sourceSpdx = rootSpdx ?? (pkgSingle.kind === 'single' ? pkgSingle.spdx : null);
  let status;
  if (conflicts.length > 0) status = 'review_required';
  else if (!sourceSpdx) status = 'blocked';
  else if (COPYLEFT_BLOCKED[sourceSpdx]) status = 'blocked';
  else if (COPYLEFT_REVIEW[sourceSpdx]) status = 'review_required';
  else if (PERMISSIVE[sourceSpdx]) status = unresolvedDep ? 'review_required' : 'clear';
  else status = 'blocked';
  for (const item of all) {
    const table = PERMISSIVE[item.spdx] ?? null;
    if (table) for (const o of table.obligations) obligations.add(o);
    if (COPYLEFT_REVIEW[item.spdx]) for (const o of COPYLEFT_REVIEW[item.spdx]) obligations.add(o);
    if (COPYLEFT_BLOCKED[item.spdx]) for (const o of COPYLEFT_BLOCKED[item.spdx]) obligations.add(o);
  }
  if (status === 'review_required') obligations.add('human_review');
  if (status === 'blocked' && sourceSpdx && COPYLEFT_BLOCKED[sourceSpdx]) obligations.add('human_review');
  const content = {
    schema_version: 1,
    source_snapshot_digest: snapshot?.source_id ?? null,
    status,
    detected,
    obligations: [...obligations].sort(),
    conflicts,
    dependency_closure_digest: objectDigest(depEntries),
    dependency_closure: closure,
    source_access_log: [],
    evidence_refs: evidence,
    disclaimer: LICENSE_DISCLAIMER,
  };
  return deepFreeze({ ...content, report_id: `license-report-${objectDigest(content).slice(7, 23)}` });
}

export function licenseReportDigest(report) {
  return objectDigest(report);
}

/** An approved review can only come from an independently constructed record. */
export function validateLicenseReviewRecord(record, { reportDigest, planDigest } = {}) {
  if (!record || typeof record !== 'object' || Array.isArray(record)) throw new Error('LICENSE_REVIEW_RECORD_INVALID');
  if (record.schema_version !== 1) throw new Error('LICENSE_REVIEW_RECORD_INVALID:schema_version');
  if (typeof record.reviewer !== 'string' || record.reviewer.length === 0) throw new Error('LICENSE_REVIEW_RECORD_INVALID:reviewer');
  if (typeof record.reviewed_at !== 'string' || Number.isNaN(Date.parse(record.reviewed_at))) throw new Error('LICENSE_REVIEW_RECORD_INVALID:reviewed_at');
  if (typeof record.scope !== 'string' || record.scope.length === 0) throw new Error('LICENSE_REVIEW_RECORD_INVALID:scope');
  if (reportDigest && record.license_report_digest !== reportDigest) throw new Error('LICENSE_REVIEW_RECORD_MISMATCH:license_report_digest');
  if (planDigest && record.transformation_plan_digest !== planDigest) throw new Error('LICENSE_REVIEW_RECORD_MISMATCH:transformation_plan_digest');
  if (record.decision !== 'approved' && record.decision !== 'rejected') throw new Error('LICENSE_REVIEW_RECORD_INVALID:decision');
  return record.decision === 'approved';
}

/**
 * Build/install gate. review_required/blocked never proceed without an
 * independent LicenseReviewRecord whose decision is 'approved'. A candidate
 * package, model message or plain JSON flag can never approve itself.
 */
export function assertLicenseCleared(report, { reviewRecord, planDigest } = {}) {
  if (!report) throw new Error('LICENSE_REPORT_REQUIRED');
  if (report.status === 'clear') return true;
  if (report.status === 'blocked') throw new Error(`LICENSE_BLOCKED:${report.detected.find(item => item.spdx)?.spdx ?? 'unknown-or-missing'}: license evidence missing, proprietary or network-copyleft; supply evidence or an independent review before any generation`);
  if (reviewRecord && validateLicenseReviewRecord(reviewRecord, { reportDigest: licenseReportDigest(report), planDigest })) return true;
  throw new Error(`LICENSE_REVIEW_PENDING:${report.detected.find(item => item.spdx)?.spdx ?? 'unknown'}: status is review_required and no independent LicenseReviewRecord approves this exact report`);
}
